// src/data/locationData.js
export const districts = [
    { name: "Nepal", code: "Nepal" },
    { name: "Bagmati (बागमती)", code: "Bagmati" },
    { name: "Gandaki (गण्डकी)", code: "Gandaki" },
    { name: "Lumbini (लुम्बिनी)", code: "Lumbini" },
    { name: "Karnali (कर्णाली)", code: "Karnali" },
    { name: "Sudurpashchim (सुदूरपश्चिम)", code: "Sudurpashchim" },
    { name: "Province 1 (प्रदेश १)", code: "Province 1" },
    { name: "Province 2 (प्रदेश २)", code: "Province 2" },
    { name: "Province 3 (प्रदेश ३)", code: "Province 3" },
    { name: "Province 4 (प्रदेश ४)", code: "Province 4" },
    { name: "Bhojpur (भोजपुर)", code: "Bhojpur" },
    { name: "Chitwan (चितवन)", code: "Chitwan" },
    { name: "Ilam (इलाम)", code: "Ilam" },
    { name: "Jhapa (झापा)", code: "Jhapa" },
    { name: "Kailali (कैलाली)", code: "Kailali" },
    { name: "Kaski (कास्की)", code: "Kaski" },
    { name: "Kathmandu (काठमाडौं)", code: "Kathmandu" },
    { name: "Khotang (खोटाङ)", code: "Khotang" },
    { name: "Lalitpur (ललितपुर)", code: "Lalitpur" },
    { name: "Makwanpur (मकवानपुर)", code: "Makwanpur" },
    { name: "Morang (मोरङ)", code: "Morang" },
    { name: "Myagdi (म्याग्दी)", code: "Myagdi" },
    { name: "Nawalpur (नवलपुर)", code: "Nawalpur" },
    { name: "Nuwakot (नुवाकोट)", code: "Nuwakot" },
    { name: "Okhaldhunga (ओखलढुंगा)", code: "Okhaldhunga" },
    { name: "Palpa (पाल्पा)", code: "Palpa" },
    { name: "Parbat (पर्वत)", code: "Parbat" },
    { name: "Patan (पाटन)", code: "Patan" },
    { name: "Panchthar (पाँचथर)", code: "Panchthar" },
    { name: "Rasuwa (रसुवा)", code: "Rasuwa" },
    { name: "Rautahat (रौतहत)", code: "Rautahat" },
    { name: "Rolpa (रोल्पा)", code: "Rolpa" },
    { name: "Rupandehi (रुपन्देही)", code: "Rupandehi" },
    { name: "Sankhuwasabha (सङ्खुवासभा)", code: "Sankhuwasabha" },
    { name: "Sarlahi (सर्लाही)", code: "Sarlahi" },
    { name: "Sindhuli (सिन्धुली)", code: "Sindhuli" },
    { name: "Sindhupalchok (सिन्धुपाल्चोक)", code: "Sindhupalchok" },
    { name: "Siraha (सिराहा)", code: "Siraha" },
    { name: "Syangja (स्याङ्जा)", code: "Syangja" },
    { name: "Tanahun (तनहुँ)", code: "Tanahun" },
    { name: "Taplejung (ताप्लेजुङ)", code: "Taplejung" },
    { name: "Terhathum (तेरथुम)", code: "Terhathum" },
    { name: "Udayapur (उदयपुर)", code: "Udayapur" },
    { name: "Surkhet (सुर्खेत)", code: "Surkhet" },
    { name: "Arghakhanchi (अर्घाखाँची)", code: "Arghakhanchi" },
    { name: "Baglung (बागलुङ)", code: "Baglung" },
    { name: "Baitadi (बैतडी)", code: "Baitadi" },
    { name: "Bardiya (बर्दिया)", code: "Bardiya" },
    { name: "Barun (बारुण)", code: "Barun" },
    { name: "Bhojpur (भोजपुर)", code: "Bhojpur" },
    { name: "Chitwan (चितवन)", code: "Chitwan" },
    { name: "Dadeldhura (दादेलधुरा)", code: "Dadeldhura" },
    { name: "Dhanusa (धनुषा)", code: "Dhanusa" },
    { name: "Dholgiri (धोलगिरी)", code: "Dholgiri" },
    { name: "Dolpa (डोल्पा)", code: "Dolpa" },
    { name: "Gulmi (गुल्मी)", code: "Gulmi" },
    { name: "Humla (हुम्ला)", code: "Humla" },
    { name: "Ilama (इलाम)", code: "Ilama" },
    { name: "Jajarkot (जाजरकोट)", code: "Jajarkot" },
    { name: "Jajarkot (जाजरकोट)", code: "Jajarkot" }
  ];
  
  